In [22]:
# Libaries

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

from sklearn.utils import resample

In [2]:
#### Preparations for the data
# Data
df = pd.read_csv(r'C:\Users\ljant\Desktop\Ironhack\07_Logarithmic_regression\lab-imbalanced-data\files_for_lab\customer_churn.csv')
def header_function (data):
    cols = []
    for i in range (len(data.columns)):
        cols.append(data.columns[i].lower().replace(' ','_'))
    
    data.columns = cols

    return data

header_function(df)

df
# 7.043 x 21

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
# Taget: churn
# independant variables: 'tenure', 'seniorcitizen','onthlycharges'

# Checking for NaN values
sum_na = df.isna().sum()
print (sum_na)

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [6]:
# Exploring data
data_types = df.dtypes
print (data_types)

print(df['churn'].unique())

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges         object
churn                object
dtype: object
['No' 'Yes']

In [7]:
# Target value --> churn
df['churn'] = df['churn'].replace({'Yes': 1, 'No': 0})
df

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,0
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,1
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,0

In [16]:
# Assessing distribution of data in terms of the target value:
df.groupby('churn').count()
#--> unbalanced data! 0 = 5.174 vs 1 = 1869

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,onlinebackup,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges
churn,,,,,,,,,,,,,,,,,,,,
0,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174,5174
1,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869,1869

In [11]:
model_df = df[['tenure', 'seniorcitizen','monthlycharges']]
model_df

      tenure  seniorcitizen  monthlycharges
0          1              0           29.85
1         34              0           56.95
2          2              0           53.85
3         45              0           42.30
4          2              0           70.70
...      ...            ...             ...
7038      24              0           84.80
7039      72              0          103.20
7040      11              0           29.60
7041       4              1           74.40
7042      66              0          105.65

[7043 rows x 3 columns]

In [12]:
# Scale/Normalise the independant variables
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
normalised_data = scaler.fit_transform(model_df)
normalised_data = pd.DataFrame(normalised_data, columns = model_df.columns)
normalised_data

        tenure  seniorcitizen  monthlycharges
0     0.013889            0.0        0.115423
1     0.472222            0.0        0.385075
2     0.027778            0.0        0.354229
3     0.625000            0.0        0.239303
4     0.027778            0.0        0.521891
...        ...            ...             ...
7038  0.333333            0.0        0.662189
7039  1.000000            0.0        0.845274
7040  0.152778            0.0        0.112935
7041  0.055556            1.0        0.558706
7042  0.916667            0.0        0.869652

[7043 rows x 3 columns]

In [13]:
# Regression model
#1. Split the data

X = model_df
Y = df['churn']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [14]:
#2. Create the model:

LR = LogisticRegression()
LR.fit(X_train, Y_train)
LR.score(X_test, Y_test)

# -> Accuracy of 76 % that I can predict the satisfaction state of a customer

# Other evaluation metrics:

predictions = LR.predict(X_test) # Here prediciting Y 

print('Accuracy is: ',  accuracy_score(Y_test, predictions))
print('Precision is: ', precision_score(Y_test, predictions))
print('Recall is: ',  recall_score(Y_test, predictions))
print('F1 is: ',  f1_score(Y_test, predictions))

print(classification_report(Y_test, predictions))

Accuracy is:  0.8055358410220014
Precision is:  0.6911196911196911
Recall is:  0.47989276139410186
F1 is:  0.5664556962025317
              precision    recall  f1-score   support

           0       0.83      0.92      0.87      1036
           1       0.69      0.48      0.57       373

    accuracy                           0.81      1409
   macro avg       0.76      0.70      0.72      1409
weighted avg       0.79      0.81      0.79      1409

In [15]:
#3. confusion matrix
confusion_matrix (Y_test, predictions)

'''
Interpretation:
- 80 customers have been falsely identified as likely to return
- 194 customers have been falsely identified as unlikely to return
--> However, even though the accuracy is high (>80%), the results are likelty not representative, because of the inbalance
    in the dataset
    
--> Accuracy is so high because the model likely predicts the majority class correctly
'''

array([[956,  80],
       [194, 179]], dtype=int64)

In [23]:
### Optimising the model
# Undersampling

# 1. Concate the train data again
train = pd.concat([X_train, Y_train], axis = 1)

# 2. Seperate minority/majority class
yes_churn = train[train['churn'] == 1]
no_churn = train[train['churn'] == 0]

display(yes_churn.shape) #1496 & 4
display(no_churn.shape) #4138 & 4

#3. Removing rows

no_churn_undersample = resample(no_churn,
                                   replace = False,
                                   n_samples = len(yes_churn),
                                   random_state = 0
                                  )

display(no_churn_undersample.shape) #1496 x 4
display(yes_churn.shape) #1496 x 4

(1496, 4)

(4138, 4)

(1496, 4)

(1496, 4)

In [24]:
#  Now the model
train_undersample = pd.concat ([no_churn_undersample, yes_churn], axis = 0)

# X-Y-Split
X_train_under = train_undersample.drop('churn', axis =1)
Y_train_under = train_undersample['churn']

# Build model
LR = LogisticRegression(max_iter = 1000)
LR.fit(X_train_under, Y_train_under)

# Predictions for test data
predictions = LR.predict(X_test) # Here prediciting Y 

print('Accuary: ', LR.score(X_test, Y_test))

print('Precision is: ', precision_score(Y_test, predictions))
print('Recall is: ',  recall_score(Y_test, predictions))
print('F1 is: ',  f1_score(Y_test, predictions))

print(classification_report(Y_test, predictions))

Accuary:  0.7452093683463449
Precision is:  0.5124555160142349
Recall is:  0.7721179624664879
F1 is:  0.616042780748663
              precision    recall  f1-score   support

           0       0.90      0.74      0.81      1036
           1       0.51      0.77      0.62       373

    accuracy                           0.75      1409
   macro avg       0.71      0.75      0.71      1409
weighted avg       0.80      0.75      0.76      1409

In [25]:
confusion_matrix (Y_test, predictions)

'''
Interpretation:
- 274 customers have been falsely identified as likely to return (before 80)
- 85 customers have been falsely identified as unlikely to return (before 194)
--> With undersampling the false negative cases have drastically decreased (recall gained 30%); Accuracy is still over >70%;
    However, precision has decreased, leaving more false posiive predictions
'''

array([[762, 274],
       [ 85, 288]], dtype=int64)

In [26]:
### Optimising the model
# Oversampling

# 1. Concate the train data again
train = pd.concat([X_train, Y_train], axis = 1)

# 2. Seperate minority/majority class
yes_churn = train[train['churn'] == 1]
no_churn = train[train['churn'] == 0]

display(yes_churn.shape) #1496 & 4
display(no_churn.shape) #4138 & 4

#3. Adding rows

yes_churn_oversample = resample(yes_churn,
                                   replace = True,
                                   n_samples = len(no_churn),
                                   random_state = 0 
                                  )

display(yes_churn_oversample.shape) #4138 x 4
display(no_churn.shape) #4138 x 4

(1496, 4)

(4138, 4)

(4138, 4)

(4138, 4)

In [32]:
#  Now the model
train_oversample = pd.concat ([yes_churn_oversample, no_churn], axis = 0)

# X-Y-Split
X_train_under = train_oversample.drop('churn', axis =1)
Y_train_under = train_oversample['churn']

# Build model
LR = LogisticRegression(max_iter = 1000)
LR.fit(X_train_under, Y_train_under)

# Predictions for test data
predictions = LR.predict(X_test) # Here prediciting Y 

print('Accuary: ', LR.score(X_test, Y_test))

print('Precision is: ', precision_score(Y_test, predictions))
print('Recall is: ',  recall_score(Y_test, predictions))
print('F1 is: ',  f1_score(Y_test, predictions))

print(classification_report(Y_test, predictions))

Accuary:  0.7459190915542938
Precision is:  0.5134168157423972
Recall is:  0.7694369973190348
F1 is:  0.6158798283261803
              precision    recall  f1-score   support

           0       0.90      0.74      0.81      1036
           1       0.51      0.77      0.62       373

    accuracy                           0.75      1409
   macro avg       0.71      0.75      0.71      1409
weighted avg       0.80      0.75      0.76      1409

In [34]:
confusion_matrix (Y_test, predictions)

'''
Interpretation:
- 272 customers have been falsely identified as likely to return (before 80)
- 86 customers have been falsely identified as unlikely to return (before 194)
--> With oversampling the false negative cases have drastically decreased (recall gained 30%); Accuracy is still over >70%;
--> In comparising with undersampling, 1 more case has been identified as false negative and 2 more as false positive 
'''

array([[764, 272],
       [ 86, 287]], dtype=int64)

In [35]:
### Optimising the model
# Oversampling - SMOTE

from imblearn.over_sampling import SMOTE

'''
By default, SMOTE uses 5 nearest neighbour points
'''

sm = SMOTE(random_state = 0, sampling_strategy = 1.0)
X_train_SMOTE, Y_train_SMOTE = sm.fit_resample(X_train, Y_train)
X_train_SMOTE

#  The model
train_oversample = pd.concat([X_train_SMOTE, Y_train_SMOTE], axis = 0)

# Build model
LR = LogisticRegression(max_iter = 1000)
LR.fit(X_train_SMOTE, Y_train_SMOTE)


# Predictions for test data
predictions = LR.predict(X_test)

print('Accuary: ', LR.score(X_test, Y_test))

print('Precision is: ', precision_score(Y_test, predictions))
print('Recall is: ',  recall_score(Y_test, predictions))
print('F1 is: ',  f1_score(Y_test, predictions))

print(classification_report(Y_test, predictions))

Accuary:  0.7452093683463449
Precision is:  0.5126811594202898
Recall is:  0.7587131367292225
F1 is:  0.6118918918918917
              precision    recall  f1-score   support

           0       0.89      0.74      0.81      1036
           1       0.51      0.76      0.61       373

    accuracy                           0.75      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.79      0.75      0.76      1409

In [36]:
confusion_matrix (Y_test, predictions)

array([[767, 269],
       [ 90, 283]], dtype=int64)

In [ ]:
'''
Interpretation:
- 269 customers have been falsely identified as likely to return (before 80)
- 90 customers have been falsely identified as unlikely to return (before 194)
--> With overrsampling with SMOT the false negative cases have drastically decreased (recall gained 30%); Accuracy is still 
    over >70%;
--> In comparising with undersampling, 5 more cases has been identified as false negative but 5 less as false positive
--> Depending on the goal of the analysis, could this be the better model than the other ones
'''